adding movie card, fixing components
auqibyousuf/TMDB-Clone-Collab pull request #11
Opened 2023-10-05 12:57 UTC by auqibyousuf

2023-10-05 13:54 UTC, UmmarHamid requested changes
The commit messages are not acceptable, also the changes w.r.t button should have been part of another PR or at-least another commit.
It becomes very hard for anyone to review

2023-10-05 13:54 UTC, UmmarHamid commented on app/components/Rating/Rating.tsx
> +// border-2 outline outline-black outline-2
lets remove this

2023-10-05 13:54 UTC, UmmarHamid commented on app/components/Rating/Rating.tsx
> +      <span className={psedoClasses} aria-hidden='true'></span>
Tailwind has something called as ring inbuilt , can you check that instead?

2023-10-05 13:54 UTC, UmmarHamid commented on app/components/Rating/Rating.tsx
> +          <sup className='text-[6px] -top-[4px]'>%</sup>
would top work here without position?

2023-10-05 13:54 UTC, UmmarHamid commented on app/components/MovieCard/MovieCard.tsx
> +      <a href='#'>
we should make this as the wrapper for the whole component

2023-10-05 13:56 UTC, auqibyousuf commented on app/components/Rating/Rating.tsx
> +          <sup className='text-[6px] -top-[4px]'>%</sup>
yes its inbuilt property of this elemt

2023-10-05 14:07 UTC, auqibyousuf commented on app/components/Rating/Rating.tsx
> +      <span className={psedoClasses} aria-hidden='true'></span>
its box shadow but here i am using different type of styling which needs psuedo classes

2023-10-06 04:41 UTC, UmmarHamid approved these changes

2023-10-06 04:51 UTC, merged