Adding movies list component and also small changes to the old components(Button,PopOver,MovieCard)
auqibyousuf/TMDB-Clone-Collab pull request #12
Opened 2023-10-06 10:52 UTC by auqibyousuf

2023-10-06 12:43 UTC, UmmarHamid reviewed
Can you add a SS so that I can review better?

2023-10-06 12:43 UTC, UmmarHamid commented on tailwind.config.ts
> +        buttonTab: 'linear-gradient(90deg, #C0FECF 0%, #1ED5A9 100%)',
we can do gradients using classes easily. do you see this buttonTab gradient reusable?
If not then we should fallback to using gradients with classes like bg-gradient-to-r  from-lightGreen to-lightBlue

2023-10-06 12:56 UTC, auqibyousuf commented on tailwind.config.ts
> +        buttonTab: 'linear-gradient(90deg, #C0FECF 0%, #1ED5A9 100%)',
did not implemented gradient i thought it will work on active button so I left it will remove this config

2023-10-06 13:01 UTC, auqibyousuf commented
<img width="1961" alt="Screenshot 2023-10-06 at 6 31 07 PM" src="https://github.com/auqibyousuf/TMDB-Clone-Collab/assets/96100051/c10f5990-d9c5-41ef-a289-f528a8eeb834">

2023-10-08 14:39 UTC, UmmarHamid requested changes
Nice work!
Small feedback

2023-10-08 14:39 UTC, UmmarHamid commented on app/components/Button/Button.tsx
> +      variant == 'tabs',
```suggestion
      variant == 'tab',
```

2023-10-08 14:39 UTC, UmmarHamid commented on app/components/MovieCard/MovieCardTypes.ts
> +  menuPopLinks: MenuPopOverTypes
```suggestion
  menuPopOverLinks: MenuPopOverTypes
```

2023-10-08 14:39 UTC, UmmarHamid commented on app/components/MovieList/MovieListTypes.ts
> +  buttonTabs: Array<ButtonType>
```suggestion
tabs?: Array<ButtonType>
```

2023-10-08 14:39 UTC, UmmarHamid commented on app/components/MovieList/MovieList.tsx
> +    </div>
```suggestion
    <div className='pl-10'>
      <div className='flex gap-5 mt-8'>
        <Heading text={title} variant='24' />
        {tabs.length>0 &&
        <div className={buttonTabClasses}>
          {buttonTabs.map((buttonTab, index) => {
            return (
              <Button
                key={index}
                text={buttonTab.text}
                variant='tabs'
                onClick={buttonTab.onClick}
                value={buttonTab.text}
              />
            )
          })}
        </div>
        }
      </div>

      <ul className={`${moviesListClasses} ${extraClasses ?? ''}`}>
        {movies.map((movie, index) => {
          return (
            <li key={index} className='flex shrink-0 basis-40'>
              <MovieCard
                cardImage={movie.cardImage}
                rating={movie.rating}
                title={movie.title}
                menuPopLinks={movie.menuPopLinks}
                date={movie.date}
              />
            </li>
          )
        })}
      </ul>
    </div>
```

2023-10-11 06:39 UTC, UmmarHamid approved these changes

2023-10-11 11:29 UTC, merged