Header component
auqibyousuf/TMDB-Clone-Collab pull request #8
Opened 2023-09-28 14:15 UTC by auqibyousuf

2023-09-28 14:34 UTC, UmmarHamid requested changes
Looks great!.

Just small nit picks

2023-09-28 14:34 UTC, UmmarHamid commented on app/components/NavBar/NavBar.tsx
> +  const listItemClasses = classNames("group p-2 pr-5 relative");
instead of padding , can we use gap-2 on the wrapper element?

2023-09-28 14:34 UTC, UmmarHamid commented on app/components/NavBar/NavBar.tsx
> +          <li key={text} className={listItemClasses}>
lets use the index here as some links may have same text

2023-09-28 14:34 UTC, UmmarHamid commented on app/components/NavBar/NavBarTypes.ts
> +  menuLinks: LinkType[];
```suggestion
  menuLinks: Array<LinkType>;
```

2023-09-28 14:34 UTC, UmmarHamid commented on app/components/Header/Header.tsx
> +      <div className={headerChildClasses}>
can we remove this element and combine the classes on the nav element?

2023-09-28 14:34 UTC, UmmarHamid commented on app/components/Header/Header.tsx
> +    "text-white w-5 h-5 pointer fill-white ml-auto"
should it use the blueish color instead?

2023-09-28 14:34 UTC, UmmarHamid commented on app/components/Header/Header.tsx
> +    "flex gap-4 items-center w-[1440px] px-10 h-full flex mx-auto"
we can use max-width instead

2023-09-28 15:28 UTC, UmmarHamid requested changes

2023-09-28 15:28 UTC, UmmarHamid commented on app/components/NavBar/NavBar.tsx
> +    </ul>
```suggestion
      {menuLinks.map((linkItem, index) => {
        const { text, url } = linkItem;
        return (
          <li
            key={index}
            className={`${listItemClasses} ${listItemExtraClasses ?? ""}`}
          >
            <LinkComponent url={url} text={text} />
          </li>
        );
      })}
    </ul>
```

2023-09-28 15:28 UTC, UmmarHamid commented on app/components/NavBar/NavBar.tsx
> +          <li key={text} className={listItemClasses}>
@auqibyousuf you missed this one?

2023-09-28 15:31 UTC, auqibyousuf commented on app/components/NavBar/NavBar.tsx
> +          <li key={text} className={listItemClasses}>
done, was showing error

2023-09-28 15:34 UTC, auqibyousuf commented
Done everything

2023-09-29 03:37 UTC, UmmarHamid approved these changes

2023-09-29 03:37 UTC, merged